  groups:
  - name: webservers
  rules:
    #- alert: healthcheck
    #  expr: vector(1)
    #  for: 60s
    #  labels:
    #    severity: critical
    #  annotations:
    #    summary: "An alert that should always be firing to certify that Alertmanager is working properly."
    #    description: |
    #      This is an alert meant to ensure that the entire alerting pipeline is functional.
    #      This alert is always firing, therefore it should always be firing in Alertmanager
    #      and always fire against a receiver. There are integrations with various notification
    #      mechanisms that send a notification when this alert is not firing. For example the
    #      "DeadMansSnitch" integration in PagerDuty.
  - alert: load
    expr: node_load1 >= 1
    for: 10s
    labels:
      severity: critical
    annotations:
      summary: "{{ $labels.instance }} - load-average"
      description: "Le server à trop de processus en attente "
  - alert: Ram Usage
    expr: "round(node_memory_MemFree_bytes  / node_memory_MemTotal_bytes,0.01)  >= 1"
    for: 10s
    labels:
      severity: critical
    annotations:
      summary: "{{ $labels.instance }} - hight cup usage"
      description: "Le server utilse plus de 80% de cpu"
