  groups:
  - name: webservers
    rules:
    - alert: load
      expr: node_load1 >= 1
      for: 10s
      labels:
        severity: critical
      annotations:
        summary: "{{ $labels.instance }} - load-average"
        description: "Le server à trop de processus en attente "
