---
hostname: grafana-demo.test
organisation: mon_organisation
mysqld_exporter_password: "secret"
grafana:
  ip: 192.168.122.229
nodes:
  - name : web-pp-1
    ip: 192.168.122.18
  - name : web-prod-1
    ip: 192.168.122.58
prometheus:
  daemon_args:
    - --web.console.templates=/var/lib/prometheus/consoles
    - --web.console.libraries=/var/lib/prometheus/console_libraries
    - --web.external-url http://192.168.122.229
alertmanager:
  version: 0.27.0
  conf: slack
slack:
  webhook: https://hooks.slack.com/services/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
