---
hostname: grafana-demo.test
organisation: mon_organisation
mysqld_exporter_password: "secret"
grafana:
  ip: 164.92.178.99
nodes:
  - name : web1
    ip: 165.227.164.114
  - name : web2
    ip: 206.81.29.155
prometheus:
  daemon_args:
    - --web.console.templates=/var/lib/prometheus/consoles
    - --web.console.libraries=/var/lib/prometheus/console_libraries
    - --web.external-url http://164.92.178.99
alertmanager:
  version: 0.27.0
  conf: slack
slack:
  webhook: https://hooks.slack.com/services/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
